# FIXME: install script doesn't handle automoation (call to chsh) well...
#- name: download oh-my-zsh install script
#  get_url:
#    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
#    dest: /tmp/install-oh-my-zsh.sh
#    mode: 0755
#
#- name: install oh-my-zsh
#  shell: /tmp/install-oh-my-zsh.sh

- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ item.username }}/.oh-my-zsh"
  with_items:
    - "{{ users }}"
  tags:
    - user

- name: setting user file permissions
  file:
    path: "/home/{{ item.username }}/.oh-my-zsh"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    recurse: yes
  with_items:
    - "{{ users }}"
  tags:
    - user

- name: setting zsh as default shell
  user:
    name: "{{ item.username }}"
    shell: /usr/bin/zsh
  with_items:
    - "{{ users }}"
  tags:
    - user

- name: configure zshrc
  template:
    src: templates/zshrc
    dest: "/home/{{ item.username }}/.zshrc"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
    backup: yes
  with_items:
    - "{{ users }}"
  tags:
    - user
    - configuration
