- name: download oh-my-zsh install script
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
    mode: 0755

- name: install oh-my-zsh
  shell: /tmp/install-oh-my-zsh.sh

- name: configure zshrc
  template:
    src: templates/zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0644
    backup: yes
