- name: add google-chrome repo
  yum_repository:
    name: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: 1
    gpgcheck: 1
    gpgkey: http://dl-ssl.google.com/linux/linux_signing_key.pub

- name: install google-chrome
  yum: name=google-chrome state=latest
