- name: determine installed ruby version
  shell: |
   {{ rvm.install_path|quote }}/bin/rvm alias list default
  register: ruby_default_version

- name: install ruby
  shell: |
    {{ rvm.install_path|quote }}/bin/rvm install {{ ruby.version|quote }}
  when: '"{{ ruby.version }}" not in ruby_default_version.stdout'

- name: set default ruby
  shell: |
    {{ rvm.install_path|quote }}/bin/rvm alias create default {{ ruby.version|quote }}

- name: install gems
  shell: |
    {{ rvm.install_path|quote }}/bin/rvm all do gem install {{ item }} --no-rdoc --no-ri
  with_items:
    - bundler
    - fpm
