- name: add wheel group
  group:
    name: wheel
    state: present

- name: allow wheel group to have NOPASSWD sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  tags:
    - users

- name: adding primary groups for users
  group:
    name: "{{ item.username }}"
    state: present
  with_items:
    - "{{ users }}"
  tags:
    - users

- name: adding user accounts
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | default(omit) }}"
    group: "{{ item.username }}"
    groups: wheel
    append: yes
  with_items:
    - "{{ users }}"
  tags:
    - users
