# {{ ansible_managed }}
ZSH=$HOME/.oh-my-zsh
ZSH_THEME='wedisagree'

CASE_SENSITIVE="true"

plugins=(colored-man docker dotenv git lein vagrant)

source "${ZSH}/oh-my-zsh.sh"

# Customize to your needs...

bindkey '\el' down-case-word
bindkey '\eu' up-case-word

export EDITOR=$(which vim)
