- name: install vagrant
  yum: name=https://releases.hashicorp.com/vagrant/{{ vagrant.version }}/vagrant_{{ vagrant.version }}_x86_64.rpm
       state=installed

- name: install vagrant plugins
  shell: "vagrant plugin install {{ item }}"
  with_items: [vagrant-lxc, vagrant-hosts]
  become: yes
  become_user: vagrant
